
# Projects
#
# Available projects are:
# examples/blinking             (blinking led controlled by main core)
# examples/dual_blinking        (two leds blinking. Each one controlled with a different core)

PROJECT_PATH ?= examples$(DS)dual_blinking

# Use if the project is not in examples folder
# PROJECT_PATH ?= examples$(DS)dual_blinking

